// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epogccddtlkuuttnfkfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwb2djY2RkdGxrdXV0dG5ma2ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODA1NTEsImV4cCI6MjA2MzE1NjU1MX0.-akURcDiJh7lJeKbuiItWJq6K6oftCk28RmnC6bwZmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);